// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: default_attrs.proto

package default_attrs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DefaultAttributes_DefaultIdTo int32

const (
	DefaultAttributes_ROOT         DefaultAttributes_DefaultIdTo = 0
	DefaultAttributes_EFFECTIVE_ID DefaultAttributes_DefaultIdTo = 1
)

// Enum value maps for DefaultAttributes_DefaultIdTo.
var (
	DefaultAttributes_DefaultIdTo_name = map[int32]string{
		0: "ROOT",
		1: "EFFECTIVE_ID",
	}
	DefaultAttributes_DefaultIdTo_value = map[string]int32{
		"ROOT":         0,
		"EFFECTIVE_ID": 1,
	}
)

func (x DefaultAttributes_DefaultIdTo) Enum() *DefaultAttributes_DefaultIdTo {
	p := new(DefaultAttributes_DefaultIdTo)
	*p = x
	return p
}

func (x DefaultAttributes_DefaultIdTo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DefaultAttributes_DefaultIdTo) Descriptor() protoreflect.EnumDescriptor {
	return file_default_attrs_proto_enumTypes[0].Descriptor()
}

func (DefaultAttributes_DefaultIdTo) Type() protoreflect.EnumType {
	return &file_default_attrs_proto_enumTypes[0]
}

func (x DefaultAttributes_DefaultIdTo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DefaultAttributes_DefaultIdTo.Descriptor instead.
func (DefaultAttributes_DefaultIdTo) EnumDescriptor() ([]byte, []int) {
	return file_default_attrs_proto_rawDescGZIP(), []int{1, 0}
}

type Vfstime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seconds  uint32 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nseconds uint32 `protobuf:"varint,2,opt,name=nseconds,proto3" json:"nseconds,omitempty"`
}

func (x *Vfstime) Reset() {
	*x = Vfstime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_default_attrs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vfstime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vfstime) ProtoMessage() {}

func (x *Vfstime) ProtoReflect() protoreflect.Message {
	mi := &file_default_attrs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vfstime.ProtoReflect.Descriptor instead.
func (*Vfstime) Descriptor() ([]byte, []int) {
	return file_default_attrs_proto_rawDescGZIP(), []int{0}
}

func (x *Vfstime) GetSeconds() uint32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Vfstime) GetNseconds() uint32 {
	if x != nil {
		return x.Nseconds
	}
	return 0
}

type DefaultAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint32                        `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Mode    uint32                        `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Uid     DefaultAttributes_DefaultIdTo `protobuf:"varint,3,opt,name=uid,proto3,enum=default_attributes.DefaultAttributes_DefaultIdTo" json:"uid,omitempty"`
	Gid     DefaultAttributes_DefaultIdTo `protobuf:"varint,4,opt,name=gid,proto3,enum=default_attributes.DefaultAttributes_DefaultIdTo" json:"gid,omitempty"`
	Atime   *Vfstime                      `protobuf:"bytes,5,opt,name=atime,proto3" json:"atime,omitempty"`
	Mtime   *Vfstime                      `protobuf:"bytes,6,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Ctime   *Vfstime                      `protobuf:"bytes,7,opt,name=ctime,proto3" json:"ctime,omitempty"`
}

func (x *DefaultAttributes) Reset() {
	*x = DefaultAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_default_attrs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultAttributes) ProtoMessage() {}

func (x *DefaultAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_default_attrs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultAttributes.ProtoReflect.Descriptor instead.
func (*DefaultAttributes) Descriptor() ([]byte, []int) {
	return file_default_attrs_proto_rawDescGZIP(), []int{1}
}

func (x *DefaultAttributes) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DefaultAttributes) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *DefaultAttributes) GetUid() DefaultAttributes_DefaultIdTo {
	if x != nil {
		return x.Uid
	}
	return DefaultAttributes_ROOT
}

func (x *DefaultAttributes) GetGid() DefaultAttributes_DefaultIdTo {
	if x != nil {
		return x.Gid
	}
	return DefaultAttributes_ROOT
}

func (x *DefaultAttributes) GetAtime() *Vfstime {
	if x != nil {
		return x.Atime
	}
	return nil
}

func (x *DefaultAttributes) GetMtime() *Vfstime {
	if x != nil {
		return x.Mtime
	}
	return nil
}

func (x *DefaultAttributes) GetCtime() *Vfstime {
	if x != nil {
		return x.Ctime
	}
	return nil
}

var File_default_attrs_proto protoreflect.FileDescriptor

var file_default_attrs_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x22, 0x3f, 0x0a, 0x07, 0x76, 0x66, 0x73,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x6e, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x8f, 0x03, 0x0a, 0x11, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x43,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73,
	0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x73, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x64, 0x54, 0x6f, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x43, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x31, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x49,
	0x64, 0x54, 0x6f, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x05, 0x61, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x66, 0x73,
	0x74, 0x69, 0x6d, 0x65, 0x52, 0x05, 0x61, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x6d,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e,
	0x76, 0x66, 0x73, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x31,
	0x0a, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x73, 0x2e, 0x76, 0x66, 0x73, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x05, 0x63, 0x74, 0x69, 0x6d,
	0x65, 0x22, 0x29, 0x0a, 0x0b, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x64, 0x54, 0x6f,
	0x12, 0x08, 0x0a, 0x04, 0x52, 0x4f, 0x4f, 0x54, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x46,
	0x46, 0x45, 0x43, 0x54, 0x49, 0x56, 0x45, 0x5f, 0x49, 0x44, 0x10, 0x01, 0x42, 0x39, 0x5a, 0x37,
	0x73, 0x69, 0x67, 0x73, 0x2e, 0x6b, 0x38, 0x73, 0x2e, 0x69, 0x6f, 0x2f, 0x62, 0x6c, 0x6f, 0x62,
	0x2d, 0x63, 0x73, 0x69, 0x2d, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x65, 0x64, 0x67, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_default_attrs_proto_rawDescOnce sync.Once
	file_default_attrs_proto_rawDescData = file_default_attrs_proto_rawDesc
)

func file_default_attrs_proto_rawDescGZIP() []byte {
	file_default_attrs_proto_rawDescOnce.Do(func() {
		file_default_attrs_proto_rawDescData = protoimpl.X.CompressGZIP(file_default_attrs_proto_rawDescData)
	})
	return file_default_attrs_proto_rawDescData
}

var file_default_attrs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_default_attrs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_default_attrs_proto_goTypes = []interface{}{
	(DefaultAttributes_DefaultIdTo)(0), // 0: default_attributes.DefaultAttributes.DefaultIdTo
	(*Vfstime)(nil),                    // 1: default_attributes.vfstime
	(*DefaultAttributes)(nil),          // 2: default_attributes.DefaultAttributes
}
var file_default_attrs_proto_depIdxs = []int32{
	0, // 0: default_attributes.DefaultAttributes.uid:type_name -> default_attributes.DefaultAttributes.DefaultIdTo
	0, // 1: default_attributes.DefaultAttributes.gid:type_name -> default_attributes.DefaultAttributes.DefaultIdTo
	1, // 2: default_attributes.DefaultAttributes.atime:type_name -> default_attributes.vfstime
	1, // 3: default_attributes.DefaultAttributes.mtime:type_name -> default_attributes.vfstime
	1, // 4: default_attributes.DefaultAttributes.ctime:type_name -> default_attributes.vfstime
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_default_attrs_proto_init() }
func file_default_attrs_proto_init() {
	if File_default_attrs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_default_attrs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vfstime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_default_attrs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_default_attrs_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_default_attrs_proto_goTypes,
		DependencyIndexes: file_default_attrs_proto_depIdxs,
		EnumInfos:         file_default_attrs_proto_enumTypes,
		MessageInfos:      file_default_attrs_proto_msgTypes,
	}.Build()
	File_default_attrs_proto = out.File
	file_default_attrs_proto_rawDesc = nil
	file_default_attrs_proto_goTypes = nil
	file_default_attrs_proto_depIdxs = nil
}
