---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob-clone
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: blob-fuse
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-blob
