---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-blob-nonroot-nfs
  labels:
    app: nginx
spec:
  serviceName: statefulset-blob-nonroot-nfs
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:  # optional just to make sure user is non-root
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: statefulset-blob
          image: andyzhangx/ubuntu1604:nonroot
          command:
            - "/bin/bash"
            - "-c"
            - set -euo pipefail; while true; do echo $(date) >> /mnt/blob/outfile; sleep 1; done
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/blob
              readOnly: false
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
      spec:
        storageClassName: blob-nfs
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 100Gi
