---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-blob-node-sa
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-blob-node-secret-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

    # the node plugin must apply finalizers to PV and PVC for edgecache volumes
    # for static pv, pv list is used to resolve volumeID --> PV mapping
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "update", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-blob-node-secret-binding
subjects:
  - kind: ServiceAccount
    name: csi-blob-node-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-blob-node-secret-role
  apiGroup: rbac.authorization.k8s.io
