{{- if .Values.rbac.create -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-{{ .Values.rbac.name }}-node-secret-role
  labels:
    {{- include "blob.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

    # the node plugin must apply finalizers to PV and PVC for edge cache volumes
    # for static pv, pv list is used to resolve volumeID --> PV mapping
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "update", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-{{ .Values.rbac.name }}-node-secret-binding
  labels:
    {{- include "blob.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.node }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-{{ .Values.rbac.name }}-node-secret-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}
