name: Static Checks
on:
    pull_request: {}
    push: {}
jobs:
    go_lint:
        name: Go Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master
            - name: Run linter
              uses: golangci/golangci-lint-action@v2
              with:
                  version: v1.45
                  # https://golangci-lint.run/usage/linters/
                  args: -E=gofmt,deadcode,unused,varcheck,ineffassign,revive,misspell,exportloopref,asciicheck,bodyclose,depguard,dogsled,dupl,durationcheck,errname,errorlint,forbidigo -D=staticcheck --timeout=30m0s
